# Generated by Django 4.1 on 2022-09-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_ipmodel_project_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='views',
        ),
        migrations.DeleteModel(
            name='IpModel',
        ),
    ]
